# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: resume.proto for package ''

require 'grpc'
require 'resume_pb'

module Details
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Details'

    rpc :getJob, Name, Job
    rpc :getInterests, Name, Interests
    rpc :getSkills, Name, Skills
    rpc :getProgrammingLanguages, Name, ProgrammingLanguages
  end

  Stub = Service.rpc_stub_class
end
